version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./initial_data.json:/docker-entrypoint-initdb.d/initial_data.json:ro

volumes:
  mongo_data:
